// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.2
// source: internal/delivery/proto/api.proto

package protocol_buffer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShowNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShowNameRequest) Reset() {
	*x = ShowNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_delivery_proto_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowNameRequest) ProtoMessage() {}

func (x *ShowNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_proto_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowNameRequest.ProtoReflect.Descriptor instead.
func (*ShowNameRequest) Descriptor() ([]byte, []int) {
	return file_internal_delivery_proto_api_proto_rawDescGZIP(), []int{0}
}

type ShowNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ShowNameResponse) Reset() {
	*x = ShowNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_delivery_proto_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowNameResponse) ProtoMessage() {}

func (x *ShowNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_proto_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowNameResponse.ProtoReflect.Descriptor instead.
func (*ShowNameResponse) Descriptor() ([]byte, []int) {
	return file_internal_delivery_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *ShowNameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StreamServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StreamServerRequest) Reset() {
	*x = StreamServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_delivery_proto_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamServerRequest) ProtoMessage() {}

func (x *StreamServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_proto_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamServerRequest.ProtoReflect.Descriptor instead.
func (*StreamServerRequest) Descriptor() ([]byte, []int) {
	return file_internal_delivery_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *StreamServerRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StreamServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *StreamServerResponse) Reset() {
	*x = StreamServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_delivery_proto_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamServerResponse) ProtoMessage() {}

func (x *StreamServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_proto_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamServerResponse.ProtoReflect.Descriptor instead.
func (*StreamServerResponse) Descriptor() ([]byte, []int) {
	return file_internal_delivery_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *StreamServerResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Channel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SendersName string `protobuf:"bytes,2,opt,name=senders_name,json=sendersName,proto3" json:"senders_name,omitempty"`
}

func (x *Channel) Reset() {
	*x = Channel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_delivery_proto_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_proto_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_internal_delivery_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Channel) GetSendersName() string {
	if x != nil {
		return x.SendersName
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel *Channel `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Message string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_delivery_proto_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_proto_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_internal_delivery_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *Message) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_delivery_proto_api_proto protoreflect.FileDescriptor

var file_internal_delivery_proto_api_proto_rawDesc = []byte{
	0x0a, 0x21, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x67, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x67, 0x6f, 0x5f,
	0x63, 0x68, 0x61, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x68, 0x6f, 0x77, 0x4e, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x26, 0x0a, 0x10, 0x53, 0x68, 0x6f, 0x77, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x25, 0x0a, 0x13, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x14, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x40, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x57, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x32, 0x0a,
	0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x67, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x67, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x90, 0x02, 0x0a, 0x08,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x51, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x77,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x2e, 0x67, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x67,
	0x6f, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x53, 0x68, 0x6f, 0x77, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x67, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x67, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x53, 0x68, 0x6f, 0x77, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x0c, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x24, 0x2e, 0x67, 0x6f,
	0x5f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x67, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x25, 0x2e, 0x67, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x67, 0x6f, 0x5f, 0x63,
	0x68, 0x61, 0x74, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x50, 0x0a, 0x14,
	0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x18, 0x2e, 0x67, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x67,
	0x6f, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x18,
	0x2e, 0x67, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x67, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x13,
	0x5a, 0x11, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x62, 0x75, 0x66,
	0x66, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_delivery_proto_api_proto_rawDescOnce sync.Once
	file_internal_delivery_proto_api_proto_rawDescData = file_internal_delivery_proto_api_proto_rawDesc
)

func file_internal_delivery_proto_api_proto_rawDescGZIP() []byte {
	file_internal_delivery_proto_api_proto_rawDescOnce.Do(func() {
		file_internal_delivery_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_delivery_proto_api_proto_rawDescData)
	})
	return file_internal_delivery_proto_api_proto_rawDescData
}

var file_internal_delivery_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_delivery_proto_api_proto_goTypes = []interface{}{
	(*ShowNameRequest)(nil),      // 0: go_chat.go_chat.ShowNameRequest
	(*ShowNameResponse)(nil),     // 1: go_chat.go_chat.ShowNameResponse
	(*StreamServerRequest)(nil),  // 2: go_chat.go_chat.StreamServerRequest
	(*StreamServerResponse)(nil), // 3: go_chat.go_chat.StreamServerResponse
	(*Channel)(nil),              // 4: go_chat.go_chat.Channel
	(*Message)(nil),              // 5: go_chat.go_chat.Message
}
var file_internal_delivery_proto_api_proto_depIdxs = []int32{
	4, // 0: go_chat.go_chat.Message.channel:type_name -> go_chat.go_chat.Channel
	0, // 1: go_chat.go_chat.Services.ShowName:input_type -> go_chat.go_chat.ShowNameRequest
	2, // 2: go_chat.go_chat.Services.StreamServer:input_type -> go_chat.go_chat.StreamServerRequest
	5, // 3: go_chat.go_chat.Services.SendMessageToChannel:input_type -> go_chat.go_chat.Message
	1, // 4: go_chat.go_chat.Services.ShowName:output_type -> go_chat.go_chat.ShowNameResponse
	3, // 5: go_chat.go_chat.Services.StreamServer:output_type -> go_chat.go_chat.StreamServerResponse
	5, // 6: go_chat.go_chat.Services.SendMessageToChannel:output_type -> go_chat.go_chat.Message
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_delivery_proto_api_proto_init() }
func file_internal_delivery_proto_api_proto_init() {
	if File_internal_delivery_proto_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_delivery_proto_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_delivery_proto_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_delivery_proto_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_delivery_proto_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_delivery_proto_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Channel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_delivery_proto_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_delivery_proto_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_delivery_proto_api_proto_goTypes,
		DependencyIndexes: file_internal_delivery_proto_api_proto_depIdxs,
		MessageInfos:      file_internal_delivery_proto_api_proto_msgTypes,
	}.Build()
	File_internal_delivery_proto_api_proto = out.File
	file_internal_delivery_proto_api_proto_rawDesc = nil
	file_internal_delivery_proto_api_proto_goTypes = nil
	file_internal_delivery_proto_api_proto_depIdxs = nil
}
